<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompaniesRepository extends EntityRepository
{

    public function findBySearch($search)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from('AppBundle\Entity\Companies', 'c')
            ->leftJoin('c.categories', 'cat') 
            ->where('c.titulo LIKE :search OR c.endereco LIKE :search OR c.cep LIKE :search OR c.cidade LIKE :search OR cat.name LIKE :search')
            ->setParameter('search', "%$search%")
            ->getQuery()
            ->getResult();
    }
}