<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySearch($search)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u')
            ->from('AppBundle\Entity\User', 'u') 
            ->where('u.username LIKE :search OR u.email LIKE :search OR u.phone LIKE :search')
            ->setParameter('search', "%$search%")
            ->getQuery()
            ->getResult();
    }
}
